cors:
  allowed-origins: http://localhost:7070

spring:
  datasource:
    url: jdbc:mysql://59.14.71.106:10039/moeum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expire: 3600000

minio:
  url: http://59.14.71.106:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}