cors:
  allowed-origins: http://localhost:7070

spring:
  datasource:
    url: jdbc:mysql://59.14.71.106:10039/moeum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PLUXITY_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  expire: 3600000

minio:
  url: http://localhost:9000
  access-key: moeum
  secret-key: moeum7192
  bucket: moeum